project:
  type: website
  output-dir: docs

website:
  title: "Megan Hoover"
  favicon: imgs/logo.png # NOTE: that the `favicon` is a `website` level option (not under `navbar`)
  navbar:
    title: false # override printing your website `title` (e.g. "megan hoover" on line 6) in the top left corner of your navbar
    logo: imgs/logo.png
    logo-alt: "Alt text for logo"
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
  page-footer:
    background: light # or `dark`
    left: Copyright 2025, Megan Hoover
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/meganhoover/meganhoover21.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
      

format:
  html:
    theme: styles.scss
    toc: true
    page-layout: full



